import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Романтический букет роз",
    description: "Изысканная композиция из 25 красных роз премиум-класса с декоративной зеленью и элегантной упаковкой",
    price: 4500,
    category: "roses",
    images: ["/luxury-red-roses-bouquet-elegant-wrapping.jpg", "/red-roses-close-up-premium-quality.jpg", "/red-roses-bouquet-side-view-elegant.jpg"],
    inStock: 12,
    featured: true,
    tags: ["романтика", "премиум", "розы"],
  },
  {
    id: "2",
    name: "Весенние тюльпаны",
    description: "Нежный букет из 51 разноцветного тюльпана в стильной упаковке",
    price: 3200,
    category: "tulips",
    images: ["/colorful-tulips-bouquet-spring-flowers.jpg", "/mixed-tulips-elegant-arrangement.jpg", "/tulips-bouquet-close-up-vibrant-colors.jpg"],
    inStock: 8,
    featured: true,
    tags: ["весна", "тюльпаны", "яркие"],
  },
  {
    id: "3",
    name: "Орхидея Фаленопсис",
    description: "Элегантная белая орхидея в керамическом кашпо премиум-класса",
    price: 5800,
    category: "orchids",
    images: ["/white-phalaenopsis-orchid-ceramic-pot-elegant.jpg", "/orchid-flowers-close-up-white-petals.jpg", "/orchid-plant-in-pot-luxury-interior.jpg"],
    inStock: 5,
    featured: true,
    tags: ["орхидеи", "премиум", "интерьер"],
  },
  {
    id: "4",
    name: 'Букет "Нежность"',
    description: "Воздушная композиция из пионовидных роз, эустомы и гортензии в пастельных тонах",
    price: 6200,
    category: "bouquets",
    images: ["/pastel-flowers-bouquet-roses-eustoma-hydrangea.jpg", "/soft-pink-flowers-arrangement-elegant.jpg", "/romantic-pastel-bouquet-luxury-wrapping.jpg"],
    inStock: 6,
    featured: true,
    tags: ["пастель", "нежность", "премиум"],
  },
  {
    id: "5",
    name: "Монобукет белых роз",
    description: "Классический букет из 15 белых роз с минималистичной упаковкой",
    price: 3800,
    category: "roses",
    images: ["/white-roses-bouquet-minimalist-elegant.jpg", "/white-roses-close-up-premium-quality.jpg", "/white-roses-arrangement-classic-style.jpg"],
    inStock: 15,
    tags: ["классика", "белые розы", "минимализм"],
  },
  {
    id: "6",
    name: 'Букет "Солнечный день"',
    description: "Яркая композиция из желтых и оранжевых цветов: розы, герберы, альстромерии",
    price: 4100,
    category: "bouquets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 10,
    tags: ["яркие", "солнечные", "радость"],
  },
  {
    id: "7",
    name: "Розовые пионы",
    description: "Роскошный букет из 11 розовых пионов с эвкалиптом",
    price: 7500,
    category: "bouquets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 4,
    featured: true,
    tags: ["пионы", "премиум", "роскошь"],
  },
  {
    id: "8",
    name: "Ваза хрустальная",
    description: "Элегантная хрустальная ваза ручной работы для букетов",
    price: 2800,
    category: "accessories",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 20,
    tags: ["ваза", "хрусталь", "аксессуары"],
  },
  {
    id: "9",
    name: 'Букет "Лавандовый сон"',
    description: "Утонченная композиция с лавандой, розами и матиолой в сиреневых тонах",
    price: 5400,
    category: "bouquets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 7,
    tags: ["лаванда", "сиреневый", "утонченность"],
  },
  {
    id: "10",
    name: "Красные тюльпаны",
    description: "Классический букет из 35 красных тюльпанов",
    price: 2900,
    category: "tulips",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 18,
    tags: ["тюльпаны", "красные", "классика"],
  },
  {
    id: "11",
    name: "Орхидея Дендробиум",
    description: "Экзотическая орхидея с фиолетовыми цветами в дизайнерском кашпо",
    price: 6500,
    category: "orchids",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 3,
    tags: ["орхидеи", "экзотика", "премиум"],
  },
  {
    id: "12",
    name: 'Букет "Шампань"',
    description: "Изысканная композиция в кремово-персиковых тонах с розами и эустомой",
    price: 5900,
    category: "bouquets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: 9,
    featured: true,
    tags: ["кремовый", "элегантность", "премиум"],
  },
]

export const categories = [
  { id: "all", name: "Все товары", count: products.length },
  { id: "bouquets", name: "Букеты", count: products.filter((p) => p.category === "bouquets").length },
  { id: "roses", name: "Розы", count: products.filter((p) => p.category === "roses").length },
  { id: "tulips", name: "Тюльпаны", count: products.filter((p) => p.category === "tulips").length },
  { id: "orchids", name: "Орхидеи", count: products.filter((p) => p.category === "orchids").length },
  { id: "accessories", name: "Аксессуары", count: products.filter((p) => p.category === "accessories").length },
]
